### ISSUE TITLE
Custom query with join returns too many rows when where references rows in the joined table

### ISSUE THREAD

**Issue by 2xbass** [rafaelwendel/phpsupabase#36]
The following query, which works as expected in Supabase: 

`select * from profiles
join team_roles on profiles.id = team_roles.profile_id
where team_roles.role_id ='ebb25d59-c23f-40f3-8c1c-9cd546d0adb8' and team_roles.team_id = '38324877-b9f9-473c-9a68-5be3f407dc86'`

is implemented using createCustomQuery with the query as follows:

`        $query = [
          'select' => '*',
          'from' => 'profiles',
          'join' => [
            [
              'table' => 'team_roles',
              'tablekey' => 'profile_id'
            ]
          ],
          'where' => [
            'team_roles.role_id' => 'eq.ebb25d59-c23f-40f3-8c1c-9cd546d0adb8',
            'team_roles.team_id' => 'eq.38324877-b9f9-473c-9a68-5be3f407dc86'
          ]
        ];`

What happens is that the query returns all the rows from the profiles table rather than just the ones it should. However the ones that it should have returned, do have teams_roles in there with the data from the columns of the joined table. This is good so I can use this to at least get the correct set of rows, but it does seem like a bug that it is returning all the other rows.

**Comment by rafaelwendel** [comment]
Hello Adrian,

It's a pleasure to talk to you.

This problem that you're having is common, because SupaBase doesn't pay much attention to PHP and therefore I end up having to think about several adaptations.

What's happening in your case is that the `team_roles` table works as a secondary table in the query, and then (I don't know why) Supabase does something like a `LEFT JOIN`, instead of an `INNER JOIN`.

My suggestion to try to solve this problem would be to invert the order of the tables, so that it looks like this:

```php
$query = [ 
    'select' => '*', 
    'from'   => 'team_roles', 
    'join'   => [ 
        [
            'table' => 'profiles', 
            'tablekey' => 'id' //PUT THE "PROFILES" PK HERE 
        ] 
    ],
    'where' => [ 
        'role_id' => 'eq.ebb25d59-c23f-40f3-8c1c-9cd546d0adb8', 
        'team_id' => 'eq.38324877-b9f9-473c-9a68-5be3f407dc86' 
    ]
];
```

The fields of the `team_roles` table will be returned normally, as well as a key called `profiles` that will contain an array with the profiles returned. Finally, instead of doing a `foreach` in `$listResult`, do it in `$listResult->profiles`.

Try it and see if it works.

Cheers
